--Oracle 18c Express Edition

alter session set "_ORACLE_SCRIPT"=true;

CREATE USER canada IDENTIFIED BY canada;
GRANT SELECT_CATALOG_ROLE TO canada;
ALTER USER canada DEFAULT ROLE ALL;
GRANT ALTER SESSION TO canada;
GRANT CREATE MATERIALIZED VIEW TO canada;
GRANT DEBUG CONNECT SESSION TO canada;
GRANT QUERY REWRITE TO canada;
GRANT CREATE ANY MATERIALIZED VIEW TO canada;
GRANT ALTER USER TO canada WITH ADMIN OPTION;
GRANT CREATE TRIGGER TO canada;
GRANT CREATE PROCEDURE TO canada;
GRANT CREATE SEQUENCE TO canada;
GRANT CREATE TABLE TO canada;
GRANT CREATE SESSION TO canada WITH ADMIN OPTION;
GRANT CREATE ANY CONTEXT TO canada;
GRANT CREATE PUBLIC SYNONYM TO canada;
GRANT ADVISOR TO canada;
GRANT CREATE TYPE TO canada;
GRANT CREATE VIEW TO canada;
GRANT CREATE SYNONYM TO canada;
GRANT CREATE DATABASE LINK TO canada;
GRANT UNLIMITED TABLESPACE TO canada;
grant connect,resource to canada;
GRANT system TO canada;
